(function () {
    "use strict";

    const execution =
        window.OAATH.ExecutionEngine;

    const tests = [];

    function test(name, fn) {
        tests.push({
            name: name,
            fn: fn
        });
    }

    function assertEqual(actual, expected, message) {
        if (actual !== expected) {
            throw new Error(
                message +
                " Expected: " +
                String(expected) +
                " Actual: " +
                String(actual)
            );
        }
    }

    function assertTrue(value, message) {
        if (value !== true) {
            throw new Error(message);
        }
    }

    function assertFalse(value, message) {
        if (value !== false) {
            throw new Error(message);
        }
    }

    function baseBoundary(maximumAmountCents) {
        return {
            boundaryId: "BOUNDARY-AUTH-105",
            sourceAuthorityId: "AUTH-105",
            actionType: "AUTO_REFUND",
            scope: {
                maximumAmountCents:
                    maximumAmountCents,
                allowedRiskLevels: [
                    "LOW",
                    "MEDIUM"
                ],
                maximumTransactionAgeDays: 30
            },
            enforceableConditions: [],
            status: "ENFORCEABLE",
            generatedFromDecisionId: "DECISION-3",
            scenarioVersion: "SCENARIO-1",
            policyVersion: "POLICY-1"
        };
    }

    function baseRequestedAction() {
        return {
            actionType: "AUTO_REFUND",
            amountCents: 40000,
            customerRisk: "MEDIUM",
            transactionAgeDays: 20
        };
    }

    function supportedCapability() {
        return {
            supported: true,
            actionType: "AUTO_REFUND",
            technicalLimitCents: 500000
        };
    }

    function passingValidity() {
        return {
            status: "PASS",
            reason: "Technical checks passed."
        };
    }

    function evaluateWith(options) {
        const settings = options || {};

        return execution.evaluateExecution({
            requestedAction:
                settings.requestedAction ||
                baseRequestedAction(),
            boundary:
                Object.prototype.hasOwnProperty.call(
                    settings,
                    "boundary"
                )
                    ? settings.boundary
                    : baseBoundary(50000),
            technicalCapability:
                settings.technicalCapability ||
                supportedCapability(),
            technicalValidity:
                settings.technicalValidity ||
                passingValidity(),
            conditionValues:
                settings.conditionValues || {}
        });
    }

    /*
     * All expected results below are manually declared.
     * No expected value is generated by ExecutionEngine.
     */

    test(
        "400 dollar refund is allowed under 500 dollar boundary",
        function () {
            const result = evaluateWith({});

            assertEqual(
                result.result,
                "ALLOW",
                "Expected manually declared ALLOW."
            );
        }
    );

    test(
        "400 dollar refund is blocked under 250 dollar boundary",
        function () {
            const result = evaluateWith({
                boundary: baseBoundary(25000)
            });

            assertEqual(
                result.result,
                "BLOCK",
                "Expected manually declared BLOCK."
            );
        }
    );

    test(
        "Boundary amount equality is allowed",
        function () {
            const request = baseRequestedAction();
            request.amountCents = 50000;

            const result = evaluateWith({
                requestedAction: request,
                boundary: baseBoundary(50000)
            });

            assertEqual(
                result.result,
                "ALLOW",
                "Amount exactly at maximum should be allowed."
            );
        }
    );

    test(
        "Action outside boundary action type is blocked",
        function () {
            const request = baseRequestedAction();
            request.actionType = "AUTO_CREDIT";

            const result = evaluateWith({
                requestedAction: request
            });

            assertEqual(
                result.result,
                "BLOCK",
                "Different action type must be blocked."
            );
        }
    );

    test(
        "Risk outside authority scope is blocked",
        function () {
            const request = baseRequestedAction();
            request.customerRisk = "HIGH";

            const result = evaluateWith({
                requestedAction: request
            });

            assertEqual(
                result.result,
                "BLOCK",
                "HIGH risk is outside manually declared scope."
            );
        }
    );

    test(
        "Transaction age above boundary is blocked",
        function () {
            const request = baseRequestedAction();
            request.transactionAgeDays = 31;

            const result = evaluateWith({
                requestedAction: request
            });

            assertEqual(
                result.result,
                "BLOCK",
                "31 days exceeds manually declared 30-day boundary."
            );
        }
    );

    test(
        "Missing boundary blocks execution",
        function () {
            const result = evaluateWith({
                boundary: null
            });

            assertEqual(
                result.result,
                "BLOCK",
                "Missing authority boundary must fail closed."
            );
        }
    );

    test(
        "Non-enforceable boundary blocks execution",
        function () {
            const boundary = baseBoundary(50000);
            boundary.status = "INVALID";

            const result = evaluateWith({
                boundary: boundary
            });

            assertEqual(
                result.result,
                "BLOCK",
                "Non-enforceable boundary must block."
            );
        }
    );

    test(
        "Unsupported technical capability blocks execution",
        function () {
            const result = evaluateWith({
                technicalCapability: {
                    supported: false,
                    actionType: "AUTO_REFUND"
                }
            });

            assertEqual(
                result.result,
                "BLOCK",
                "Unsupported capability must block."
            );
        }
    );

    test(
        "Technical validity FAIL blocks execution",
        function () {
            const result = evaluateWith({
                technicalValidity: {
                    status: "FAIL",
                    reason: "Technical validation failed."
                }
            });

            assertEqual(
                result.result,
                "BLOCK",
                "Technical validity FAIL must block."
            );
        }
    );

    test(
        "Technical validity PASS does not override insufficient authority",
        function () {
            const result = evaluateWith({
                boundary: baseBoundary(25000),
                technicalValidity: {
                    status: "PASS",
                    reason: "Technical validation passed."
                }
            });

            assertEqual(
                result.result,
                "BLOCK",
                "PASS cannot create authority."
            );
        }
    );

    test(
        "Required boolean condition satisfied allows execution",
        function () {
            const boundary = baseBoundary(50000);

            boundary.enforceableConditions = [
                {
                    required: true,
                    predicate: {
                        field: "supervisorConfirmation",
                        operator: "EQ",
                        comparisonValue: true,
                        valueType: "boolean"
                    }
                }
            ];

            const result = evaluateWith({
                boundary: boundary,
                conditionValues: {
                    supervisorConfirmation: true
                }
            });

            assertEqual(
                result.result,
                "ALLOW",
                "Satisfied required condition should permit evaluation to continue."
            );
        }
    );

    test(
        "Required boolean condition false blocks execution",
        function () {
            const boundary = baseBoundary(50000);

            boundary.enforceableConditions = [
                {
                    required: true,
                    predicate: {
                        field: "supervisorConfirmation",
                        operator: "EQ",
                        comparisonValue: true,
                        valueType: "boolean"
                    }
                }
            ];

            const result = evaluateWith({
                boundary: boundary,
                conditionValues: {
                    supervisorConfirmation: false
                }
            });

            assertEqual(
                result.result,
                "BLOCK",
                "Unsatisfied required condition must block."
            );
        }
    );

    test(
        "Missing required condition value blocks execution",
        function () {
            const boundary = baseBoundary(50000);

            boundary.enforceableConditions = [
                {
                    required: true,
                    predicate: {
                        field: "supervisorConfirmation",
                        operator: "EQ",
                        comparisonValue: true,
                        valueType: "boolean"
                    }
                }
            ];

            const result = evaluateWith({
                boundary: boundary,
                conditionValues: {}
            });

            assertEqual(
                result.result,
                "BLOCK",
                "Missing required condition input must fail closed."
            );
        }
    );

    test(
        "Malformed required condition blocks execution",
        function () {
            const boundary = baseBoundary(50000);

            boundary.enforceableConditions = [
                {
                    required: true,
                    predicate: {
                        field: "supervisorConfirmation",
                        operator: "MAGIC",
                        comparisonValue: true,
                        valueType: "boolean"
                    }
                }
            ];

            const result = evaluateWith({
                boundary: boundary,
                conditionValues: {
                    supervisorConfirmation: true
                }
            });

            assertEqual(
                result.result,
                "BLOCK",
                "Malformed condition must fail closed."
            );
        }
    );

    test(
        "Optional condition is not required for execution",
        function () {
            const boundary = baseBoundary(50000);

            boundary.enforceableConditions = [
                {
                    required: false,
                    predicate: {
                        field: "supervisorConfirmation",
                        operator: "EQ",
                        comparisonValue: true,
                        valueType: "boolean"
                    }
                }
            ];

            const result = evaluateWith({
                boundary: boundary,
                conditionValues: {}
            });

            assertEqual(
                result.result,
                "ALLOW",
                "Optional condition should not block when absent."
            );
        }
    );

    test(
        "Execution result references evaluated boundary",
        function () {
            const result = evaluateWith({});

            assertEqual(
                result.boundaryId,
                "BOUNDARY-AUTH-105",
                "Execution result must identify evaluated boundary."
            );
        }
    );

    test(
        "Execution result is deeply frozen",
        function () {
            const result = evaluateWith({});

            assertTrue(
                Object.isFrozen(result),
                "Execution result should be frozen."
            );
        }
    );

    test(
        "Execution reports all simultaneous enforceable-boundary violations",
        function () {
            const boundary = baseBoundary(25000);
            boundary.scope.allowedRiskLevels = ["LOW"];
            boundary.enforceableConditions = [
                {
                    required: true,
                    predicate: {
                        field: "supervisorConfirmation",
                        operator: "EQ",
                        comparisonValue: true,
                        valueType: "boolean"
                    }
                }
            ];

            const result = evaluateWith({
                boundary: boundary,
                conditionValues: {
                    supervisorConfirmation: false
                }
            });

            assertEqual(
                result.result,
                "BLOCK",
                "Multiple violations must still block."
            );

            assertTrue(
                result.reason.includes(
                    "Requested amount exceeds"
                ) &&
                result.reason.includes(
                    "customer risk"
                ) &&
                result.reason.includes(
                    "supervisorConfirmation"
                ),
                "Execution reason should identify every simultaneous boundary violation."
            );
        }
    );

    test(
        "Generic integer scope constraint allows an in-bound action",
        function () {
            const boundary = baseBoundary(50000);
            boundary.scope = {
                constraints: [
                    {
                        field: "resultingWeeklyHours",
                        operator: "LTE",
                        comparisonValue: 40,
                        valueType: "integer"
                    }
                ]
            };
            boundary.actionType = "ASSIGN_SHIFT";

            const result = evaluateWith({
                requestedAction: {
                    actionType: "ASSIGN_SHIFT",
                    resultingWeeklyHours: 40
                },
                boundary: boundary
            });

            assertEqual(
                result.result,
                "ALLOW",
                "A generic in-bound integer constraint should allow execution."
            );
        }
    );

    test(
        "Generic integer scope constraint blocks an out-of-bound action",
        function () {
            const boundary = baseBoundary(50000);
            boundary.scope = {
                constraints: [
                    {
                        field: "resultingWeeklyHours",
                        operator: "LTE",
                        comparisonValue: 40,
                        valueType: "integer"
                    }
                ]
            };
            boundary.actionType = "ASSIGN_SHIFT";

            const result = evaluateWith({
                requestedAction: {
                    actionType: "ASSIGN_SHIFT",
                    resultingWeeklyHours: 48
                },
                boundary: boundary
            });

            assertEqual(
                result.result,
                "BLOCK",
                "A generic out-of-bound integer constraint should block execution."
            );

            assertTrue(
                result.reason.includes("resultingWeeklyHours"),
                "Generic block evidence should identify the violated field."
            );
        }
    );

    test(
        "Generic IN scope constraint evaluates string membership",
        function () {
            const boundary = baseBoundary(50000);
            boundary.scope = {
                constraints: [
                    {
                        field: "accessLevel",
                        operator: "IN",
                        comparisonValue: ["READ_ONLY"],
                        valueType: "string"
                    }
                ]
            };
            boundary.actionType = "GRANT_ACCESS";

            const result = evaluateWith({
                requestedAction: {
                    actionType: "GRANT_ACCESS",
                    accessLevel: "PRODUCTION_ADMIN"
                },
                boundary: boundary
            });

            assertEqual(
                result.result,
                "BLOCK",
                "A value outside a generic IN constraint should block execution."
            );
        }
    );

    const summary =
        document.getElementById(
            "execution-summary"
        );

    const resultList =
        document.getElementById(
            "execution-results"
        );

    let passed = 0;

    tests.forEach(function (item) {
        const row =
            document.createElement("li");

        try {
            item.fn();

            row.textContent =
                item.name + ": PASS";

            row.setAttribute(
                "data-execution-test-status",
                "PASS"
            );

            passed += 1;
        }
        catch (error) {
            row.textContent =
                item.name +
                ": " +
                error.message;

            row.setAttribute(
                "data-execution-test-status",
                "FAIL"
            );
        }

        resultList.appendChild(row);
    });

    summary.textContent =
        passed +
        "/" +
        tests.length +
        " execution tests passed.";

    summary.setAttribute(
        "data-execution-passed",
        String(passed)
    );

    summary.setAttribute(
        "data-execution-total",
        String(tests.length)
    );

    summary.setAttribute(
        "data-execution-status",
        passed === tests.length
            ? "PASS"
            : "FAIL"
    );
}());